In [5]:
import numpy as np


In [ ]:
# 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [7]:
res = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print(res)

[1 2 3 4 5 6 7 8 9 0]


In [ ]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [8]:
res = np.zeros((3, 3))
print(res)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть 
# його значення.

In [9]:
res = np.random.randint(1, 10, (5, 5))
print(res)

[[2 9 1 3 8]
 [9 6 7 9 1]
 [4 1 7 8 3]
 [6 4 7 6 1]
 [4 8 8 9 6]]


In [ ]:
# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть 
#його значення.

In [10]:
res = np.random.random((4, 4))
print(res)

[[0.06733511 0.15592558 0.21783117 0.57706466]
 [0.18335501 0.6866233  0.62939798 0.05171945]
 [0.52766141 0.26089556 0.59354635 0.42252157]
 [0.91754189 0.84285076 0.73110509 0.82794135]]


In [ ]:
# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні 
# від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [18]:
a = np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)
print(f'a = {a}\nb = {b}\n')
print(f' a + b = {a + b}')
print(f' a - b = {a - b}')
print(f' a * b = {a * b} ')

a = [1 9 4 7 3]
b = [2 3 8 8 5]

 a + b = [ 3 12 12 15  8]
 a - b = [-1  6 -4 -1 -2]
 a * b = [ 2 27 32 56 15] 


In [ ]:
# 6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [19]:
a = np.array([1, 4, 8, 9])
b = np.array([2, 5, 6, 6])
print(np.dot(a, b))

124


In [ ]:
# 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та 
# перемножте їх між собою.

In [20]:
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 3))
print(np.dot(a, b))

[[96 96 86]
 [92 82 87]]


In [ ]:
# 8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та 
# знайдіть її обернену матрицю.

In [22]:
a = np.random.randint(1, 10, (3, 3))
print(np.linalg.inv(a))

[[ 0.13352273 -0.16761364  0.07102273]
 [ 0.08238636  0.08806818 -0.10511364]
 [-0.12784091  0.13920455  0.05965909]]


In [ ]:
# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та 
# транспонуйте її.

In [28]:
a = np.random.random((4, 4))
print(f' simple matrix is:\n\n {a}\n')
print( f' trans matrix is :\n\n {a.T}')

 simple matrix is:

 [[0.36527978 0.17756363 0.13380411 0.36472347]
 [0.34548176 0.24977178 0.20951583 0.2615354 ]
 [0.05649664 0.69603147 0.7854515  0.311597  ]
 [0.90672528 0.82528402 0.97524652 0.83613882]]

 trans matrix is :

 [[0.36527978 0.34548176 0.05649664 0.90672528]
 [0.17756363 0.24977178 0.69603147 0.82528402]
 [0.13380411 0.20951583 0.7854515  0.97524652]
 [0.36472347 0.2615354  0.311597   0.83613882]]


In [ ]:
# 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні
# від 1 до 10 та перемножте матрицю на вектор.

In [29]:
matrix = np.random.randint(1, 10, (3, 4))
vector = np.random.randint(1, 10, 4)
print(matrix * vector)

[[21 40 20  6]
 [18  8  4 36]
 [24 48  4 36]]


In [ ]:
# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні 
# від 0 до 1 та перемножте матрицю на вектор.

In [30]:
matrix = np.random.random((2, 3))
vector = np.random.random(3)
print( matrix * vector)

[[0.06929286 0.09486405 0.75252421]
 [0.04011553 0.16989563 0.20121425]]


In [ ]:
# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та 
# виконайте їхнє поелементне множення.

In [31]:
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
print(a * b)

[[36  8]
 [ 4 25]]


In [ ]:
# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 
# та знайдіть їх добуток.

In [32]:
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
print(np.dot(a, b))

[[25 21]
 [58 47]]


In [ ]:
# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та 
# знайдіть суму елементів матриці.

In [33]:
a = np.random.randint(1, 10, (5, 5))
print(np.sum(a))

116


In [ ]:
# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та 
# знайдіть їхню різницю.

In [34]:
a = np.random.randint(1, 10, (4, 4))
b = np.random.randint(1, 10, (4, 4))
print(a - b)

[[-3  2 -2 -3]
 [ 0  0  0  1]
 [ 3 -1 -5  2]
 [-2  1 -1  4]]


In [ ]:
# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та 
# знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [38]:
mat = np.random.random((3, 3))
print(sum(mat.T))

[1.18595169 1.78742942 1.44711698]


In [ ]:
# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел. 

In [35]:
matrix = np.array([[3, 4, 2, 1], [1, 2, 3, 5], [1, 1, 2, 2]])
print( matrix ** 2)

[[ 9 16  4  1]
 [ 1  4  9 25]
 [ 1  1  4  4]]


In [ ]:
# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та 
#знайдіть вектор з квадратними коренями цих чисел.

In [36]:
vector = np.random.randint(1, 50, 4)
print(vector ** 0.5)

[1.73205081 6.32455532 6.63324958 4.35889894]
